# Generated by Django 3.2.16 on 2022-12-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
